version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  spark:
    image: bitnami/spark:3.3.1
    container_name: spark
    environment:
      - SPARK_MODE=master
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "8082:8080"
      - "7077:7077"
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode

  spark-worker:
    image: bitnami/spark:3.3.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "8081:8081"
    networks:
      - hadoop
    depends_on:
      - spark

networks:
  hadoop:

volumes:
  namenode:
  datanode:
